### ISSUE TITLE
Add support for variable name change.

### ISSUE THREAD

**Issue by datawater** [atifaziz/CSharpMinifier#37]
Many minifiers look through the code, detect variable names and change them to short, generated labels. Generated variable names can come from an "iterator" of the alphabet, Ex:

| Index | Output |
|-----|-----|
| 0   | a   |
| 1   | b   |
| ... | ... | 
| 52  | aa  |

**Comment by atifaziz** [comment]
This is deliberately out-of-scope and stated in the [read-me document](https://github.com/atifaziz/CSharpMinifier/blob/fcb5b93a134aef8ae9045ed1cf602ec419d8152c/README.md?plain=1#L13-L14):

> It is a _minifier_ but not an _obfuscator_ or an _uglifier_; that is, private details like local variable names are not abbreviated.

The idea is to keep the minifier simple, fast and dependency-free by focusing mostly on the [lexical grammar of the C# language](https://github.com/dotnet/csharpstandard/blob/V6-standard/standard/lexical-structure.md#623-lexical-grammar). Beyond that, it also deals with [string literals](https://github.com/dotnet/csharpstandard/blob/V6-standard/standard/lexical-structure.md#6456-string-literals). This too is [stated in the read-me](https://github.com/atifaziz/CSharpMinifier/blob/fcb5b93a134aef8ae9045ed1cf602ec419d8152c/README.md?plain=1#L53-L56):

> For the purpose of minification, especially that of whitespace and comments, CSharpMinifier needs to ensure that it does not confuse, for example, a comment appearing in a string or a commented-out string. Therefore it parses some minimal grammar of a C# source, such as: …

If the variables names are changed, then the following scenario goes out the door:

> …it is best used for computing hashes or digests for the purpose of detecting _potentially useful_ as opposed to any _physical changes_.

If you want to minify the variable names, you can use Roslyn for syntactic analysis after putting a source through CSharpMinifier. However, to pull that of correctly, it requires a much deeper analysis, especially of lexical scope due to the possibility of name shadowing in lamdas and local functions. Finally, if you're using Roslyn then you probably can do most of the work of CSharpMinifier easily without CSharpMinifier.

I'll close this for now on the basis of the feature request being out-of-scope, but happy to reconsider if you have some other arguments in mind.
